name: Regression Tests

on:
  workflow_dispatch: {}
  schedule:
    # Run nightly at 02:00 UTC
    - cron: '0 2 * * *'

jobs:
  regression:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run full test suite (regression)
        run: npm test
